### ISSUE TITLE
想加入学习调试技术，怎么联系

### ISSUE THREAD

**Issue by xioabudian** [chenzhiy2001/code-debug#21]
If submitting a bug please make sure

- [ ] If you are using gdb
  - [ ] `gdb --version` >= 7.7.1
  - [ ] it works on the command line with `gdb`
  - [ ] `cwd` and `target` are properly set
- [ ]  If you are using lldb
  - [ ] `lldb --version` >= 3.7.1
  - [ ] it works on the command line with `lldb-mi`
  - [ ] `cwd` and `target` are properly set

Screenshots are helpful but not required

**Comment by chenzhiy2001** [comment]
您好，可以加下我微信：untilthedayibecome

**Comment by chenzhiy2001** [comment]
> If submitting a bug please make sure
> 
> * [ ]  If you are using gdb
>   
>   * [ ]  `gdb --version` >= 7.7.1
>   * [ ]  it works on the command line with `gdb`
>   * [ ]  `cwd` and `target` are properly set
> * [ ]   If you are using lldb
>   
>   * [ ]  `lldb --version` >= 3.7.1
>   * [ ]  it works on the command line with `lldb-mi`
>   * [ ]  `cwd` and `target` are properly set
> 
> Screenshots are helpful but not required

您好，可以加下我微信：untilthedayibecome

**Comment by xioabudian** [comment]
您好，已加
