### ISSUE TITLE
[Discussion] Does this project need a prettier?

### ISSUE THREAD

**Issue by werifu** [chenzhiy2001/code-debug#3]
项目问题：
原仓库没有对代码风格进行自动化的修正，每个人编写时会使用自己的默认VSCode风格（比如tab缩进单元、单双引号），作为多人协作项目可能面临代码格式差别过大导致可读性下降以及不一致的问题，同时自己进行 format 时可能会影响到其他人的代码，不利于对 pr 的 code review（虽然不一定有）

解决方案：
配置一个统一的.prettier，尽量遵从原仓库的代码风格，如：不使用空格代替tab、缩进2格、使用双引号来表示字符串等，以减少对原仓库的影响，同时

缺陷：
因为原仓库代码风格本身也不是很一致，因此第一次 format 一定会对现有代码产生大量的变更，现在已有的工作可能需要解决大量的冲突。

不知大家有什么看法，是否需要一个自动格式化工具以方便项目的可持续性维护？

**Comment by chenzhiy2001** [comment]
我觉得可以，现在的代码风格很混乱，可读性很差
字符串引号都是混用的，箭头函数的缩进也不统一
