### ISSUE TITLE
rCore-ebpf支持

### ISSUE THREAD

**Issue by chenzhiy2001** [chenzhiy2001/code-debug#5]
1. 解决硬编码问题，让rCore兼容此插件
然后有三种办法
1. watchpoint
2. 不用gdb
    1. 实现`mi2.ts`接口
    2. ebpf输入输出符合GDB/MI（重写`mibase.ts`）
3. gdb执行函数
    1. rust支持

**Comment by hm1229** [comment]
that's a good idea

**Comment by chenzhiy2001** [comment]
It is being implemented
